# Generated by Django 5.0.6 on 2024-06-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpayment',
            options={'verbose_name_plural': 'Payments'},
        ),
    ]
