# Generated by Django 5.0.6 on 2024-06-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_cashpayment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashpayment',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='cashpayment',
            old_name='participant_id',
            new_name='participant',
        ),
    ]
